TOP=../..

include $(TOP)/configure/CONFIG
#================================================
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#================================================

LIBRARY_IOC += timeStampSource

DBD += timeStampSource.dbd
INC += registerTimeStampSource.c

timeStampSource_DBD += timeStampSource.dbd

timeStampSource_SRCS += timeStampSource.c
timeStampSource_SRCS += registerTimeStampSource.c
timeStampSource_SRCS += devTimeStampSource.c

#==================================================

include $(TOP)/configure/RULES

#==================================================
#  ADD RULES AFTER THIS LINE

