TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

DB += NDStats2.template
DB += profile2.template

include $(TOP)/configure/RULES
