TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

# Rules for installing EDM files:
CFG +=  CONFIG_EDL

# Low-level stats displays
EDLS += ProfileMonitor.edl
EDLS += ProfileMonitorHis.edl
EDLS += ProfileMonitorOffline.edl
EDLS += ProfileTrigger-lowlevel.edl
EDLS += ProfileTrigger.edl

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
